In [1]:
import numpy as np

In [2]:
x = np.array([2,4,5,7,9,8,6])
x

array([2, 4, 5, 7, 9, 8, 6])

In [3]:
l = [[1,2,3],[3,4,5],[5,6,7],[7,8,9]]
y = np.array(l)
y

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7],
       [7, 8, 9]])

In [29]:
l1 = []
l2 = []
for i in y:
    for j in i:
        if j%2==0:
            l1.append(j)
        else:
            l2.append(j)
print(l1)
print(l2)

[2, 4, 6, 8]
[1, 3, 3, 5, 5, 7, 7, 9]


In [23]:
len(y.flatten())

12

In [17]:
y[1:3,2:3]

array([[5],
       [7]])

In [4]:
y.ndim

2

In [5]:
y.shape

(4, 3)

In [6]:
a = np.array([2,4,8,34,65,84,4])
a

array([ 2,  4,  8, 34, 65, 84,  4])

In [8]:
a[a>50]

array([65, 84])

In [9]:
# to change datatype
b = np.array(a,dtype = float)
b

array([ 2.,  4.,  8., 34., 65., 84.,  4.])

In [11]:
a[(a<10) | (a>15)]

array([ 2,  4,  8, 34, 65, 84,  4])

In [12]:
~a[(a <11) | (a>15)]

array([ -3,  -5,  -9, -35, -66, -85,  -5], dtype=int32)

In [18]:
b = np.array([[[[1,2,3],[4,5,6],[7,8,9]]]])
#you have to fetch 6
b

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]]])

In [20]:
b[0][0][1:2,2:3]

array([[6]])

In [21]:
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
l1 = []
l2 = []
for i in b:
    for j in i:
        if j%2==0:
            l1.append(j)
        else:
            l2.append(j)
            

In [31]:
b.ravel() # to convert 2D or 3D into 1D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
# broadcasting

s = np.array([[1,2,3],[4,5,6],[20,30,40]])
s

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [20, 30, 40]])

In [35]:
s*100+2

array([[ 102,  202,  302],
       [ 402,  502,  602],
       [2002, 3002, 4002]])

In [37]:
s.reshape(3,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [20, 30, 40]])

In [39]:
p= np.array([1,2,3,4,5,6,7,8,9,10.20,30,40])
p

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. ,  9. , 10.2, 30. ,
       40. ])

In [41]:
p.reshape(4,3)

array([[ 1. ,  2. ,  3. ],
       [ 4. ,  5. ,  6. ],
       [ 7. ,  8. ,  9. ],
       [10.2, 30. , 40. ]])

In [44]:
x = lambda s,t: s*t

In [46]:
x(3,4)

12

In [47]:
a = lambda a,b:a+b
a(np.array([20,10,50]),np.array([60,10,26]))

array([80, 20, 76])